### ISSUE TITLE
Which SDK revision this repository is based on?

### ISSUE THREAD

**Issue by K4thos** [cvet/fonline_tla#14]
Hi,
Not strictly an issue but a question (posted here because for some reason my account on http://fonline.ru is still not activated by admin even though I created it a week ago).

1. I'm wondering what is the SDK revision number that this TLA repository is meant to work with. Renaming "Modules" to "ProjectFiles" in FOnline.cfg is a change introduced in REV 798, but the presence of #include "Tla" suggests that the correct SDK should be older than REV 646 where #include, shared, import features have been disabled (these lines results in "Runtime assert: includeDeep <= 1 in Script.cpp (1065)" error in latest SDK).

What I'm trying to do is find the last SDK where this updated repository works as indented and then try to update it from there up to the latest SDK (or at least use the SDK that this TLA version is based on if I won't be able to update TLA content based on SDK commit logs).

2. With the recent changes in this repository I'm wondering if you are planning to update TLA content yourself, Cvet, to work with latest SDK at some point?

Thanks in advance for answers.

**Comment by cvet** [comment]
Hello!
Current TLA content are not adopted for last SDK revision.
I just made some actualization for config and batch files and change project hierarchy.
But all scripts, protos, maps, etc are still in some old state.
I need contributers for making this job.

**Comment by K4thos** [comment]
Thank you for quick reply. Maybe I will be able to help with updating TLA content considering I need this base before I start my standalone Fallout project (writing all game logic from scratch would be a nightmare). Can't promise that I will succeed with just SDK changes commit logs but it's worth a try. 

As mentioned I'm interested in knowing the exact revision number that this repository can be used on (ignoring those recent changes in bat and config of course). There are quite a few changes in GUI and scripts code in this repository compared to TLA content included in REV 605 (the last SDK that had TLA content included), so I'm not sure which SDK revision should I download to get this repository to start without errors.

**Comment by cvet** [comment]
Yes, you right!
I did revert sdk to rev. 605.

**Comment by K4thos** [comment]
thank you for answering my questions. I'm closing the issue.
